import {signOut, useSession} from "next-auth/react";
import {useRouter} from "next/dist/client/router";
import Head from "next/head";
import React from "react";

export default function Home() {
    const {data: session} = useSession();
    const router = useRouter();

    console.log("session", session);

    return (
        <div>

            <Head>
                <title>PRO-NET</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <div class="container">
                <header class="blog-header lh-1 py-3">
                    <div class="row flex-nowrap justify-content-between align-items-center">
                        <div class="col-4 pt-1">
                            <svg className="svg-icon" viewBox="0 0 20 20">
                                <path fill="none"
                                      d="M18.21,16.157v-8.21c0-0.756-0.613-1.368-1.368-1.368h-1.368v1.368v1.368v6.841l-1.368,3.421h5.473L18.21,16.157z"></path>
                                <path fill="none"
                                      d="M4.527,9.316V7.948V6.579H3.159c-0.756,0-1.368,0.613-1.368,1.368v8.21l-1.368,3.421h5.473l-1.368-3.421V9.316z"></path>
                                <path fill="none"
                                      d="M14.766,5.895h0.023V5.21c0-2.644-2.145-4.788-4.789-4.788S5.211,2.566,5.211,5.21v0.685h0.023H14.766zM12.737,3.843c0.378,0,0.684,0.307,0.684,0.684s-0.306,0.684-0.684,0.684c-0.378,0-0.684-0.307-0.684-0.684S12.358,3.843,12.737,3.843z M10,1.448c0.755,0,1.368,0.613,1.368,1.368S10.755,4.185,10,4.185c-0.756,0-1.368-0.613-1.368-1.368S9.244,1.448,10,1.448z"></path>
                                <path fill="none"
                                      d="M14.789,6.579H5.211v9.578l1.368,1.368h6.841l1.368-1.368V6.579z M12.052,12.052H7.948c-0.378,0-0.684-0.306-0.684-0.684c0-0.378,0.306-0.684,0.684-0.684h4.105c0.378,0,0.684,0.306,0.684,0.684C12.737,11.746,12.431,12.052,12.052,12.052z M12.052,9.316H7.948c-0.378,0-0.684-0.307-0.684-0.684s0.306-0.684,0.684-0.684h4.105c0.378,0,0.684,0.307,0.684,0.684S12.431,9.316,12.052,9.316z"></path>
                            </svg>
                        </div>
                        <div class="col-4 text-center">
                            <a className="blog-header-logo text-dark display-4" href="#">PRO-NET</a>
                        </div>
                        <div class="col-4 d-flex justify-content-end align-items-center">
                            {session ? (<button className="btn btn-sm btn-outline-dark"  onClick={() => signOut()}>Log out</button>)
                                : (<button className="btn btn-sm btn-outline-dark"  onClick={() => {router.push("/api/auth/signin");}}>Sign in</button>)}
                        </div>
                    </div>
                </header>
            </div>

            <main class="container">
                <div class="md-5 my-4 rounded text-bg-dark row align-items-center">
                    <div class="p-lg-5 p-md-3 col-md-7 justify-center align-middle">
                        <h3 className="display-6 fst-italic">
                            {session ? (session.user.username + ' que bueno tenerte de vuelta en el centro de capacitación PRO-NET')
                                : ('Bienvenido al centro de capacitación PRO-NET')}

                        </h3>
                        <p className="lead my-3">Multiple lines of text that form the lede, informing new readers quickly
                            and efficiently about what’s most interesting in this post’s contents.</p>
                        <p class="lead mb-0"><a href="#" className="text-white fw-bold">Continue reading...</a></p>
                    </div>
                    < div class="col-md-5">
                        < img src="https://i.pinimg.com/originals/bc/d2/9e/bcd29e2049a3365941de6b624058fc9a.png"
                              className="img-fluid" alt="Phone image"/>
                    < /div>
                </div>

                <div class="row mb-2">
                    <div class="col-md-6">
                        <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                            <div class="col p-4 d-flex flex-column position-static">
                                <strong class="d-inline-block mb-2 text-primary">Style</strong>
                                <h3 class="mb-0">Featured post</h3>
                                <div class="mb-1 text-muted">Nov 12</div>
                                <p class="card-text mb-auto">This is a wider card with supporting text below as a
                                    natural lead-in to additional content.</p>
                                <a href="#" className="stretched-link">Continue reading</a>
                            </div>
                            <div class="col-5 d-none d-lg-block">
                                < img src="https://cdni.iconscout.com/illustration/premium/thumb/painter-3235451-2694561.png"
                                      className="img-fluid" alt="Phone image"/>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div
                            class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                            <div class="col p-4 d-flex flex-column position-static">
                                <strong class="d-inline-block mb-2 text-success">Design</strong>
                                <h3 class="mb-0">Post title</h3>
                                <div class="mb-1 text-muted">Nov 11</div>
                                <p class="mb-auto">This is a wider card with supporting text below as a natural lead-in
                                    to additional content.</p>
                                <a href="#" className="stretched-link">Continue reading</a>
                            </div>
                            <div class="col-4 d-none d-lg-block py-3">
                                < img src="https://cdni.iconscout.com/illustration/free/thumb/online-learning-concept-2043016-1742871.png"
                                      className="img-fluid" alt="Phone image"/>
                            </div>
                        </div>
                    </div>
                </div>

            </main>

        </div>
    )
}